### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [javamanatee/peter-kropotkin_memoirs-of-a-revolutionist#1]
# general issues:

- [x] `se find-mismatched-diacritics .` provides several hits. You can standardize Kazan/Kazán and any others related to Russian locations. Make sure this is in an [Editorial] commit.

# preface.xhtml:

- [x] Since this is not a letter, `se:letter.dateline` semantics is not appropriate. You can use  a `<time>` element.

# chapter-1-3.xhtml:

- [x] `Con amore` is in MW. Remove the italics.

# chapter-2-1.xhtml:

- [x] Move the semicolon outside the italics for `<i xml:lang="fr">pages de chambre;</i>`.

# chapter-4-9.xhtml:

- [x] It looks like `goodhearted` is missing a dash. Make sure this is in an [Editorial] commit.

# chapter-6-14.xhtml:

- [x] There is a typo in `Quand è voir?`

# content.opf:

- [x] The LCSH term IDs should be just the numeric values starting with "sh" instead of URLs. See the example below [SEMOS 9.5.1.5.2.2](https://standardebooks.org/manual/1.7.4/single-page#9.5.1.5.2.2).

- [x] Remove the proper name from the short description ([SEMOS 9.6.1.2](https://standardebooks.org/manual/1.7.4/single-page#9.6.1.2)).

**Comment by javamanatee** [comment]
For "con amore" I thought 8.2.9.9 would apply, but perhaps not in this case, so I removed the italics.
I standardized Kazán, and I think the other mismatches are due to language or some other difference, like Kara Sea and Kará region of Siberia. Back over to you.
